In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
a = np.array([1,2,3]) # numpy array 1 dimensi
print(a)
a

[1 2 3]


array([1, 2, 3])

In [7]:
b = [1,2,3]
print(b)
b

[1, 2, 3]


[1, 2, 3]

In [11]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) # numpy array 2 dimensi
print(c)
c

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
d = [[1,2,3],[4,5, 6],[7,8,9]]
print(d)
d

[[1, 2, 3], [4, 5], [7, 8, 9]]


[[1, 2, 3], [4, 5], [7, 8, 9]]

jumlah item dalam sebuah numpy array secara row (axis 2) harus imbang, selalu sama.

setiap row punya jumlah item yang sama.

shortcut lain untuk buat numpy array selain np.array([]):

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.empty(18) # secara teori isinya kosong

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34609790e-307,
       1.06809792e-306, 1.78020440e-306, 3.56043054e-307, 6.23047163e-307,
       1.33512308e-306, 6.23037317e-307, 2.22522597e-306, 1.33511969e-306,
       1.42419666e-306, 1.05694828e-307, 1.16820707e-307, 9.34569726e-307,
       9.34564294e-307, 8.34402697e-308])

In [18]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
lima = np.arange(5,101,5)
lima

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

### add, remove, sort

In [23]:
a = np.zeros(2)
b = np.ones(3)

np.append(a, b)

array([0., 0., 1., 1., 1.])

In [24]:
np.append(a, [1,2,3])

array([0., 0., 1., 2., 3.])

In [27]:
np.delete(lima, 1)

array([  5,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [29]:
acak = np.array([12,6,23,78,9,4,-12,4-9,0])
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [34]:
tersortir = np.sort(acak)
tersortir

array([-12,  -5,   0,   4,   6,   9,  12,  23,  78])

In [33]:
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

### melihat shape dan size array

In [42]:
array3d = np.array([
    [[1,2,1,2],[3,4,2,1]],
    [[5,6,7,8],[7,8,6,5]],
    [[9,0,3,5],[1,2,3,45]]
])

In [43]:
np.ndim(array3d)

3

In [44]:
np.shape(array3d)
# kita akan dapat (3, 2, 4) yang artinya di level pertama ada 3 item
# setiap item tersebut (level2) isinya ada 2 element
# setiap element tersebut (level3) ada 4 barang lagi

(3, 2, 4)

In [48]:
np.size(array3d)

24

In [39]:
array3d.ndim

3

In [45]:
array3d.shape

(3, 2, 4)

In [47]:
array3d.size

24

### reshape

In [49]:
hasil_reshape = array3d.reshape(4,6)
hasil_reshape

array([[ 1,  2,  1,  2,  3,  4],
       [ 2,  1,  5,  6,  7,  8],
       [ 7,  8,  6,  5,  9,  0],
       [ 3,  5,  1,  2,  3, 45]])

In [50]:
hasil_reshape = array3d.reshape(24,1)
hasil_reshape

array([[ 1],
       [ 2],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 2],
       [ 1],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 7],
       [ 8],
       [ 6],
       [ 5],
       [ 9],
       [ 0],
       [ 3],
       [ 5],
       [ 1],
       [ 2],
       [ 3],
       [45]])

In [51]:
hasil_reshape = array3d.reshape(2,3,4)
hasil_reshape

array([[[ 1,  2,  1,  2],
        [ 3,  4,  2,  1],
        [ 5,  6,  7,  8]],

       [[ 7,  8,  6,  5],
        [ 9,  0,  3,  5],
        [ 1,  2,  3, 45]]])

### menambah dimensi array

In [62]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [54]:
arr.ndim

1

In [59]:
arr2 = arr[np.newaxis, :] # merubah array 1 dimensi menjadi 2 dimensi. cara lain: np.expand_dims(arr, axis=0)
arr2

array([[0, 1, 2, 3, 4, 5]])

In [57]:
arr2.ndim

2

In [61]:
arr3 = arr[:, np.newaxis] # merubah array 1 dimensi menjadi 2 dimensi. cara lain: np.expand_dims(arr, axis=1)
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

apa perbedaan arr[np.newaxis, :] dengan arr[:, np.newaxis]?

bedany adalah axis mana yang ditambahkan menjadi dimensi baru. 

untuk yang pertama, dia akan tambahin di axis 0 (row).

untuk yang kedua, dia akan tambahin di axis 1 (column).

In [63]:
# cara lain selain pakai np.newaxis adalah dengan pakai np.expand_dims
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [64]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4, 5]])

### indexing dan slicing
indexing adalah mengambil 1 item di array/list menggunakan index nya

slicing adalah mengambil satu set item di array/list menggunakan index juga

In [65]:
arr

array([0, 1, 2, 3, 4, 5])

In [66]:
arr[0:3] # membuat array baru yang isinya ada 3 item, diambil dari arr index ke 0 sampai index ke 2

array([0, 1, 2])

In [67]:
arr[-2:] # membuat array baru yang isinya ada 2 item, diambil dari arr index ke -2 sampai terakhir

array([4, 5])

In [68]:
arr[3]

3

In [72]:
new = arr[1:5] # kalau hasilnya mau disimpan, masukkan ke variable
new

array([1, 2, 3, 4])

In [71]:
arr # arr tidak diubah oleh indexing ataupun slicing

array([0, 1, 2, 3, 4, 5])

In [78]:
acak = np.array([12,6,23,78,9,4,-12,4-9,0])
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [75]:
acak[acak > 0] # numpy array bisa terima kondisi sebagai index nya juga

array([12,  6, 23, 78,  9,  4])

In [76]:
acak # tetap tidak merubah array awalnya

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [79]:
lebih_dari_0 = (acak > 0)
acak[lebih_dari_0]

array([12,  6, 23, 78,  9,  4])

In [80]:
acak_genap = acak[acak % 2 == 0] # kita ambil angka yang genap saja
acak_genap

array([ 12,   6,  78,   4, -12,   0])

In [81]:
acak_genap_lebih_dari_0 = acak[(acak % 2 == 0) & (acak > 0)] # kita ambil angka yang genap dan lebih dari 0
acak_genap_lebih_dari_0

array([12,  6, 78,  4])

In [82]:
acak_genap_lebih_dari_0 = acak[(acak % 2 == 0) | (acak > 0)] # kita ambil angka yang genap atau lebih dari 0
acak_genap_lebih_dari_0

array([ 12,   6,  23,  78,   9,   4, -12,   0])

### teknik lain untuk membuat numpy array
- vstack: vertical stack
- hstack: horizontal stack
- hsplit: horizontal split

In [84]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arr_tumpuk12 = np.vstack((arr1, arr2))
# jadilah sebuah array 2 dimensi hasil "menumpuk" atau "stack"
# arr1 dan arr2:
arr_tumpuk12

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [85]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20,21],[22,23],[24,25]])
arr_tumpuk12 = np.vstack((arr1, arr2))
arr_tumpuk12

array([[10, 11],
       [12, 13],
       [14, 15],
       [20, 21],
       [22, 23],
       [24, 25]])

In [88]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20,21, 22,23, 24,25]])
arr_tumpuk12 = np.vstack((arr1, arr2))
# error vstack terjadi saat mencoba menumpuk array yang tidak
# sama ukuran row nya. yg arr1 ada 2, yg arr2 ada 6, tidak pas.
arr_tumpuk12

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 6

In [94]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
arr_tumpuk12 = np.hstack((arr1, arr2))
# horizontal stack menumpuk juga tapi dari kiri ke kanan
arr_tumpuk12

array([10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25])

In [95]:
arr1

array([10, 11, 12, 13, 14, 15])

In [96]:
arr2

array([20, 21, 22, 23, 24, 25])

In [100]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20],[22],[24]])
arr_tumpuk12 = np.hstack((arr1, arr2))
arr_tumpuk12

array([[10, 11, 20],
       [12, 13, 22],
       [14, 15, 24]])

In [101]:
arr1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [102]:
arr2

array([[20],
       [22],
       [24]])

In [103]:
arr1 = np.array([[10,11],[12,13],[14,15]])
arr2 = np.array([[20,21, 22,23, 24,25]])
arr_tumpuk12 = np.hstack((arr1, arr2))
arr_tumpuk12

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [104]:
arr1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [105]:
arr2

array([[20, 21, 22, 23, 24, 25]])

hsplit membagi satu array jadi banyak

In [107]:
arr3 = np.array([[10, 11, 12, 13, 14, 15],
                 [20, 21, 22, 23, 24, 25]])
arr3.size

12

In [114]:
hasil_split = np.hsplit(arr3,3) # membuat array baru dari array lama
hasil_split

[array([[10, 11],
        [20, 21]]),
 array([[12, 13],
        [22, 23]]),
 array([[14, 15],
        [24, 25]])]

In [109]:
arr3 # array awal tidak berubah

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [112]:
hasil_split[0] 
# karena hasil split nya ada 3, diberikan dalam bentuk list
# kita bisa ambil menggunakan index

array([[10, 11],
       [20, 21]])

In [115]:
# karena arr3 isinya ada 12 item, dia bisa dibagi 3.
# misalkan kita bagi 7, pembagiannya gak imbang, ini akan error
np.hsplit(arr3,7)

ValueError: array split does not result in an equal division

In [116]:
# view, arr4 hanya menunjuk ke rumah arr3, shallow copy
arr4 = arr3.view()

# copy, arr4 membuat rumah sendiri dan mengisi dengan item yang sama
# dengan arr3 punya, deep copy
arr4 = arr3.copy()

### numpy array isinya bisa dihitung langsung
sebuah numpy array bisa kita tambah kurang kali bagi dll ke angka
atau ke numpy array lain

In [122]:
arr3 = np.array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])
arr3

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [123]:
arr3 + 1 # hasilnya kalau mau disimpan, masukkan ke variable

array([[11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26]])

In [124]:
arr3 - 10

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

In [125]:
arr3 * 2

array([[20, 22, 24, 26, 28, 30],
       [40, 42, 44, 46, 48, 50]])

In [126]:
arr3 / 5

array([[2. , 2.2, 2.4, 2.6, 2.8, 3. ],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ]])

In [127]:
arr3.sum()

210

In [129]:
arr5 = np.array([[5],[10]])
arr5.sum() # semua item ditambah jadi 1 item

15

In [131]:
arr3

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [130]:
arr3.sum(axis=0) #semua row isinya ditambah jadi 1 row

array([30, 32, 34, 36, 38, 40])

In [132]:
arr3.sum(axis=1) #semua kolom isinya ditambah jadi 1 kolom

array([ 75, 135])

In [133]:
panjang = np.array([30,20,40,15])
lebar = np.array([20,10,50,70])
tinggi = np.array([5,10,15,20])

In [136]:
area = panjang * lebar
area

array([ 600,  200, 2000, 1050])

In [138]:
volume = area * tinggi
volume

array([ 3000,  2000, 30000, 21000])

In [139]:
hari_senin = np.array([10,20,50])
hari_selasa = np.array([100,0,10])

penjualan = hari_senin + hari_selasa
penjualan

array([110,  20,  60])

## array operation lainnya
- maximum
- minimum
- sum (jumlah)
- mean (rata-rata)

In [141]:
acak = np.array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])
acak

array([ 12,   6,  23,  78,   9,   4, -12,  -5,   0])

In [142]:
acak.max()

78

In [143]:
acak.min()

-12

In [144]:
acak.sum()

115

In [145]:
acak.mean()

12.777777777777779

In [146]:
# kita buat matrix dulu
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
print(M.sum(axis=0))
print(M.mean(axis=0))
print(M.max(axis=0))
print(M.min(axis=0))

[12 15 18]
[4. 5. 6.]
[7 8 9]
[1 2 3]


In [148]:
print(M.sum(axis=1))
print(M.mean(axis=1))
print(M.max(axis=1))
print(M.min(axis=1))

[ 6 15 24]
[2. 5. 8.]
[3 6 9]
[1 4 7]


- product (dot product untuk matrix)
- standard deviation (angka statistik)

visualisasi dot product bisa dilihat di website ini https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [151]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [7,8],
    [9,10],
    [11,12]
])

In [152]:
np.dot(A, B)

array([[ 58,  64],
       [139, 154]])

In [154]:
np.std(A) # apa gunanya angka ini? tunggu sesi 9

1.707825127659933

### transpose vs reshape

In [158]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [157]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### mengurangi dimensi sebuah numpy array
- flatten: bikin array baru, deep
- ravel: referensi array lama, shallow

In [159]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
A.flatten() # bikin array baru

array([1, 2, 3, 4, 5, 6])

In [161]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

### formula matematika
bisa ditulis di python menggunakan bantuan Numpy array

In [165]:
a = np.array([[1,2,3]])
b = np.array([[9,10,11]])
print(a.shape, b.shape)
b = b.T
print(b.shape)

(1, 3) (1, 3)
(3, 1)


In [166]:
np.dot(a,b)

array([[62]])